alter session set "_oracle_script"=true;
create user COMERCIO identified by COMERCIO;
GRANT CONNECT, RESOURCE, DBA TO COMERCIO;

CREATE TABLE ARTICULOS(
	ARTICULO VARCHAR2(20),
	COD_FABRICANTE NUMBER(3),
	PESO NUMBER(3),
	CATEGORIA VARCHAR2(10),
	PRECIO_VENTA NUMBER(4,2),
	PRECIO_COSTO NUMBER(4,2),
	EXISTENCIAS NUMBER(5),
	CONSTRAINT PK_ARTICULOS PRIMARY KEY (ARTICULO,COD_FABRICANTE,PESO,CATEGORIA),
	CONSTRAINT CHK1_ARTICULOS CHECK (PRECIO_VENTA>0 AND PRECIO_COSTO>0 AND PESO>0),
	CONSTRAINT CHK2_CATEGORIA CHECK  (CATEGORIA='PRIMERA' OR CATEGORIA='SEGUNDA' OR CATEGORIA='TERCERA')
);
CREATE TABLE TIENDAS(
	NIF VARCHAR2(9),
	NOMBRE VARCHAR2(20),
	DIRECCION VARCHAR2(20),
	POBLACION VARCHAR2(20),
	PROVINCIA VARCHAR2(20),
	CODPOSTAL NUMBER(5),
	CONSTRAINT PK_NIF PRIMARY KEY (NIF),
	CONSTRAINT CHK_PROVINCIA CHECK (UPPER(PROVINCIA)=PROVINCIA)
);
CREATE TABLE FABRICANTES(
	COD_FABRICANTE NUMBER(3),
	NOMBRE VARCHAR2(15),
	PAIS VARCHAR2(15),
	CONSTRAINT PK_CODFABRICANTE PRIMARY KEY (COD_FABRICANTE),
	CONSTRAINT CHK_FABRICANTE CHECK (UPPER(NOMBRE)=NOMBRE AND UPPER(PAIS)=PAIS)
);
ALTER TABLE ARTICULOS ADD CONSTRAINT FK_CODFRABIRCANTE FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE);
CREATE TABLE PEDIDOS(
	NIF VARCHAR2(10),
	ARTICULO VARCHAR2(20),
	COD_FABRICANTE NUMBER(3),
	PESO NUMBER(3),
	CATEGORIA VARCHAR2(10),
	FECHA_PEDIDO DATE,
	UNIDADES_PEDIDAS NUMBER(4),
	CONSTRAINT PK_PEDIDOS PRIMARY KEY (NIF,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,FECHA_PEDIDO),
	CONSTRAINT FK_CODFRABRICANTE FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE),
	CONSTRAINT CHK3_UNIDADES CHECK (UNIDADES_PEDIDAS>0),
	CONSTRAINT FK2_ARTICULOS FOREIGN KEY (ARTICULO,COD_FABRICANTE,PESO,CATEGORIA) REFERENCES ARTICULOS(ARTICULO,COD_FABRICANTE,PESO,CATEGORIA) ON DELETE CASCADE,
	CONSTRAINT FK_NIFTIENDA FOREIGN KEY (NIF) REFERENCES TIENDAS(NIF)
);
CREATE TABLE VENTAS(
	NIF VARCHAR2(10),
	ARTICULO VARCHAR2(20),
	COD_FABRICANTE NUMBER(3),
	PESO NUMBER(3),
	CATEGORIA VARCHAR2(10),
	FECHA_VENTA DATE DEFAULT SYSDATE,
	UNIDADES_VENDIDAS NUMBER(4),
	CONSTRAINT PK1_VENTAS PRIMARY KEY (NIF,ARTICULO,COD_FABRICANTE,PESO,CATEGORIA,FECHA_VENTA),
	CONSTRAINT FK2_CODFRABRICANTE FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE),
	CONSTRAINT CHK4_UNIDADESVEND CHECK (UNIDADES_VENDIDAS>0),
	CONSTRAINT FK2_NIFTIENDA FOREIGN KEY (NIF) REFERENCES TIENDAS(NIF)
);
--1. Modificar las columnas de las tablas pedidos y ventas para que las unidades_vendidas y las unidades_pedidas puedan almacenar cantidades numéricas de 6 dígitos.
ALTER TABLE PEDIDOS MODIFY UNIDADES_PEDIDAS NUMBER(6);
ALTER TABLE VENTAS MODIFY UNIDADES_VENDIDAS NUMBER(6);
--2. Añadir a las tablas pedidos y ventas una nueva columna para que almacenen el PVP del artículo.
ALTER TABLE PEDIDOS ADD PVP NUMBER(6);
ALTER TABLE VENTAS ADD PVP NUMBER(6);
--3. Borra la columna pais de la tabla fabricante.
ALTER TABLE FABRICANTES DROP CONSTRAINT CHK_FABRICANTE; 
ALTER TABLE FABRICANTES DROP COLUMN PAIS; 
ALTER TABLE FABRICANTES ADD CONSTRAINT CHK_FABRICANTE CHECK (UPPER(NOMBRE)=NOMBRE);
--4. Añade una restricción que indique que las unidades vendidas son como mínimo 100
ALTER TABLE VENTAS ADD CONSTRAINT CHK_UNIDADESVENDIDAS CHECK (UNIDADES_VENDIDAS >= 100);
--5. Borra la restricción anterior
ALTER TABLE VENTAS DROP CONSTRAINT CHK_UNIDADESVENDIDAS;
--6. Borra todas las tablas creadas.
DROP TABLE VENTAS; 
DROP TABLE PEDIDOS;
DROP TABLE TIENDAS;
DROP TABLE ARTICULOS;
DROP TABLE FABRICANTES;