--BOLETIN 1
--1
SELECT A.NOMBRE ,A.APELLIDOS 
FROM AFILIADOS a 
WHERE UPPER(A.SEXO) LIKE 'H'
AND 1070 > EXTRACT(YEAR FROM (A.NACIMIENTO)) ;
--2
SELECT C.PESO ,C.TALLA ,C.PEZ 
FROM CAPTURASEVENTOS c
WHERE C.TALLA <=45
ORDER BY C.PEZ ,C.PESO DESC,C.TALLA DESC; 
--3
SELECT A.NOMBRE ,A.APELLIDOS ,A.TELF 
FROM AFILIADOS a ,PERMISOS p 
WHERE A.FICHA = P.FICHA 
AND P.LICENCIA LIKE 'A%' OR P.LICENCIA LIKE 'a%'
AND A.DIRECCION LIKE 'Avda%'
AND A.TELF LIKE '9%';
--4
SELECT DISTINCT L.LUGAR,L.COMUNIDAD ,L.CAUCE 
FROM LUGARES l ,CAPTURASSOLOS c 
WHERE L.LUGAR = C.LUGAR
AND C.PEZ LIKE 'Tenca';
--5
SELECT A.NOMBRE ,A.APELLIDOS 
FROM AFILIADOS a ,PARTICIPACIONES p ,EVENTOS e  
WHERE A.FICHA = P.FICHA  
AND E.EVENTO = P.EVENTO 
AND P.TROFEO IS NOT NULL
ORDER BY E.FECHA_EVENTO DESC;
--6
SELECT DISTINCT a.NOMBRE || ' '|| a.APELLIDOS AS Concursante , a2.NOMBRE ||' '|| a2.APELLIDOS AS Segundo_Aval 
FROM AFILIADOS a , CAPTURASSOLOS c , AFILIADOS a2 
WHERE a.FICHA = c.FICHA AND a2.FICHA = c.AVAL2 ;
--7
SELECT P.EVENTO 
FROM PARTICIPACIONES p ,EVENTOS e 
WHERE P.EVENTO = E.EVENTO 
AND P.FICHA = 3796
AND 1995 = EXTRACT (YEAR FROM (E.FECHA_EVENTO))
AND P.TROFEO IS NULL;
--8
SELECT COUNT(DISTINCT C.PEZ)
FROM CAPTURASSOLOS c;
--9
SELECT L.CAUCE
FROM LUGARES l 
GROUP BY L.CAUCE 
HAVING 1<COUNT(L.LUGAR);
--10
SELECT E.LUGAR
FROM EVENTOS e 
GROUP BY E.LUGAR 
HAVING 0 = COUNT(E.EVENTO);
--11
SELECT COUNT(C.PEZ),L.CAUCE 
FROM CAPTURASEVENTOS c ,EVENTOS e ,LUGARES l 
WHERE C.EVENTO = E.EVENTO 
AND E.LUGAR = L.LUGAR 
GROUP BY L.CAUCE
ORDER BY L.CAUCE,COUNT(C.PEZ) DESC;
--12
SELECT A.NOMBRE
FROM EVENTOS e ,CAPTURASEVENTOS c ,AFILIADOS a 
WHERE A.FICHA =C.FICHA  
AND E.EVENTO = C.EVENTO 
GROUP BY A.NOMBRE
HAVING 10 <= COUNT(DISTINCT LUGAR);
--13
SELECT A.NOMBRE ,COUNT(C.PEZ) 
FROM CAPTURASSOLOS c ,AFILIADOS a 
WHERE C.FICHA = A.FICHA 
GROUP BY A.NOMBRE;
SELECT NOMBRE FROM (SELECT a.NOMBRE, count(c.PEZ)
FROM AFILIADOS a , CAPTURASSOLOS c 
WHERE a.FICHA = c.FICHA  
GROUP BY a.NOMBRE 
ORDER BY count(c.pez) DESC)
WHERE rownum=1;
--14
SELECT DISTINCT  a.NOMBRE || ' ' || a.APELLIDOS AS Primer_Aval, a2.NOMBRE || ' ' || a2.APELLIDOS AS Segundo_Aval
FROM AFILIADOS a , AFILIADOS a2 , CAPTURASSOLOS c 
WHERE a.FICHA = c.AVAL1 AND a2.FICHA = c.AVAL2 ;



