CREATE TABLE TEMA
(
	COD_TEMA NUMBER(20),
	DENOMINACION VARCHAR2(15),
	COD_TEMA_PADRE NUMBER(20),
	CONSTRAINT PK_TEMA PRIMARY KEY (COD_TEMA),
	CONSTRAINT FK1_TEMA FOREIGN KEY (COD_TEMA_PADRE) REFERENCES TEMA(COD_TEMA)
);

CREATE TABLE LIBRO
(
	COD_LIBRO VARCHAR2(15),
	TITULO VARCHAR2(20),
	FECHA_CREACION DATE,
	COD_TEMA NUMBER(20),
	AUTOR_PRINCIPAL VARCHAR2(10),
	CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIBRO),
	CONSTRAINT FK1_LIBRO FOREIGN KEY (COD_TEMA) REFERENCES TEMA(COD_TEMA)
);


CREATE TABLE AUTOR
(
	COD_AUTOR VARCHAR2(10),
	NOMBRE VARCHAR2(15),
	FECHA_NACIMIENTO DATE,
	LIBRO_PRINCIPAL VARCHAR(15),
	CONSTRAINT PK_AUTOR PRIMARY KEY (COD_AUTOR),
	CONSTRAINT FK1_AUTOR FOREIGN KEY (LIBRO_PRINCIPAL) REFERENCES LIBRO(COD_LIBRO)
);

CREATE TABLE LIBRO_AUTOR
(
	COD_LIBRO VARCHAR2(15),
	COD_AUTOR VARCHAR2(10),
	ORDEN VARCHAR2(20),
	CONSTRAINT PK_LIBRO_AUTOR PRIMARY KEY (COD_LIBRO,COD_AUTOR),
	CONSTRAINT FK1_LIBRO_AUTOR FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
	CONSTRAINT FK2_LIBRO_AUTOR FOREIGN KEY (COD_AUTOR) REFERENCES AUTOR(COD_AUTOR)
);

CREATE TABLE PUBLICACIONES
(
	COD_EDITORIAL VARCHAR2(10),
	COD_LIBRO VARCHAR2(15),
	PRECIO NUMBER(5) NOT NULL,
	FECHA_PUBLICACION DATE,
	CONSTRAINT PK_PUBLICACIONES PRIMARY KEY (COD_EDITORIAL,COD_LIBRO),
	CONSTRAINT FK1_PUBLICACIONES FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO)
);

CREATE TABLE EDITORIAL
(
	COD_EDITORIAL VARCHAR2(10),
	DENOMINACION VARCHAR2(15),
	CONSTRAINT PK_EDITORIAL PRIMARY KEY (COD_EDITORIAL)
);



--FOREIGN KEYS--
ALTER TABLE LIBRO ADD CONSTRAINT FK2_LIBRO FOREIGN KEY (AUTOR_PRINCIPAL) REFERENCES AUTOR(COD_AUTOR);
ALTER TABLE PUBLICACIONES ADD CONSTRAINT FK2_PUBLICACIONES FOREIGN KEY (COD_EDITORIAL) REFERENCES EDITORIAL(COD_EDITORIAL) ON DELETE CASCADE;

--NOTAS A TENER EN CUENTA--
ALTER TABLE LIBRO_AUTOR ADD CONSTRAINT CHK1_ORDEN CHECK (ORDEN IN ('1','2','3','4','5'));

ALTER TABLE TEMA ADD CONSTRAINT CHK1_COD_TEMA CHECK (COD_TEMA_PADRE > COD_TEMA);

ALTER TABLE PUBLICACIONES MODIFY FECHA_PUBLICACION DEFAULT SYSDATE;

ALTER TABLE PUBLICACIONES ADD CONSTRAINT CHK1_PRECIO CHECK (PRECIO > 0);

--BORRAR TABLAS CREADAS--

DROP TABLE AUTOR CASCADE CONSTRAINTS;
DROP TABLE EDITORIAL CASCADE CONSTRAINTS;
DROP TABLE LIBRO CASCADE CONSTRAINTS;
DROP TABLE LIBRO_AUTOR CASCADE CONSTRAINTS;
DROP TABLE PUBLICACIONES CASCADE CONSTRAINTS;
DROP TABLE TEMA CASCADE CONSTRAINTS;


