alter session set "_oracle_script"=true;
create user JARDINERIA identified by JARDINERIA;
GRANT CONNECT, RESOURCE, DBA TO JARDINERIA;

CREATE TABLE GAMA_PRODUCTO(
GAMA VARCHAR2(50),
DESCRIPCION_TEXTO VARCHAR2(50),
DESCRIPCION_HTML VARCHAR2(50),
IMAGEN VARCHAR2(256),
CONSTRAINT PK_GAMA PRIMARY KEY (GAMA)
);
CREATE TABLE PRODUCTO(
CODIGO_PRODUCTO VARCHAR2(15),
NOMBRE VARCHAR(70),
GAMA VARCHAR2(50),
DIMENSIONES VARCHAR2(25),
PROVEEDOR VARCHAR(50),
DESCRIPCION VARCHAR2(50),
CANTIDAD_EN_STOCK NUMBER(6),
PRECIO_VENTA NUMBER(15,2),
PRECIO_PROVEEDOR NUMBER(15,2),
CONSTRAINT PK_CODIGO_PRODUCTO PRIMARY KEY (CODIGO_PRODUCTO)
);
CREATE TABLE PEDIDO(
CODIGO_PEDIDO NUMBER(11),
FECHA_PEDIDO DATE,
FECHA_ESPERADA DATE,
FECHA_ENTREGA DATE,
ESTADO VARCHAR2(15),
COMENTARIOS VARCHAR2(50),
CODIGO_CLIENTE NUMBER(11),
CONSTRAINT PK_CODIGO_PEDIDO PRIMARY KEY (CODIGO_PEDIDO)
);
CREATE TABLE DETALLE_PEDIDO(
CODIGO_PEDIDO NUMBER(11),
CODIGO_PRODUCTO VARCHAR2(15),
CANTIDAD NUMBER(11),
PRECIO_UNIDAD NUMBER(15,2),
NUMERO_LINEA NUMBER(6),
CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (CODIGO_PEDIDO,CODIGO_PRODUCTO)
);
CREATE TABLE CLIENTE(
CODIGO_CLIENTE NUMBER(11),
NOMBRE_CLIENTE VARCHAR2(50),
NOMBRE_CONTACTO VARCHAR2(30),
APELLIDO_CONTACTO VARCHAR(30),
TELEFONO VARCHAR2(15),
FAX VARCHAR2(15),
LINEA_DIRECCION1 VARCHAR2(50),
LINEA_DIRECCION2 VARCHAR2(50),
CIUDAD VARCHAR2(50),
REGION VARCHAR2(50),
PAIS VARCHAR2(50),
CODIGO_POSTAL VARCHAR2(10),
CODIGO_EMPLEADO_REP_VENTAS NUMBER(11),
LIMITE_CREDITO DECIMAL(15,2),
CONSTRAINT PK_CODIGO_CLIENTE PRIMARY KEY (CODIGO_CLIENTE)
);
CREATE TABLE PAGO(
CODIGO_CLIENTE NUMBER(11),
FORMA_PAGO VARCHAR2(40),
ID_TRANSACCION VARCHAR2(50),
FECHA_PAGO DATE,
TOTAL NUMBER(15,2),
CONSTRAINT PK_ID_TRANSACCION PRIMARY KEY (ID_TRANSACCION)
);
CREATE TABLE EMPLEADO(
CODIGO_EMPLEADO NUMBER(11),
NOMBRE VARCHAR2(50),
APELLIDO1 VARCHAR2(50),
APELLIDO2 VARCHAR2(50),
EXTENSION VARCHAR2(10),
EMAIL VARCHAR2(100),
CODIGO_OFICINA VARCHAR2(10),
CODIGO_JEFE NUMBER(11),
PUESTO VARCHAR2(50),
CONSTRAINT PK_CODIGO_EMPLEADO PRIMARY KEY (CODIGO_EMPLEADO)
);
CREATE TABLE OFICINA(
CODIGO_OFICINA VARCHAR2(10),
CIUDAD VARCHAR2(30),
PAIS VARCHAR2(50),
REGION VARCHAR2(50),
CODIGO_POSTAL VARCHAR2(10),
TELEFONO VARCHAR2(20),
LINEA_DIRECCION1 VARCHAR2(50),
LINEA_DIRECCION2 VARCHAR2(50),
CONSTRAINT PK_CODIGO_OFICINA PRIMARY KEY (CODIGO_OFICINA)
);

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_GAMA FOREIGN KEY (GAMA) REFERENCES GAMA_PRODUCTO(GAMA);
ALTER TABLE DETALLE_PEDIDO ADD CONSTRAINT FK_CODIGO_PRODUCTO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO);
ALTER TABLE DETALLE_PEDIDO ADD CONSTRAINT FK_CODIGO_PEDIDO FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO(CODIGO_PEDIDO);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_CODIGO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE);
ALTER TABLE PAGO ADD CONSTRAINT FK2_CODIGO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE);
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CODIGO_EMPLEADO FOREIGN KEY (CODIGO_EMPLEADO_REP_VENTAS) REFERENCES EMPLEADO(CODIGO_EMPLEADO);
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_CODIGO_OFICINA FOREIGN KEY (CODIGO_OFICINA) REFERENCES OFICINA(CODIGO_OFICINA);
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_CODIGO_JEFE FOREIGN KEY (CODIGO_JEFE) REFERENCES EMPLEADO(CODIGO_EMPLEADO);
