create database JARDINERIA;
create user 'JARDINERIA'@'%' identified by 'JARDINERIA';
grant all on JARDINERIA.* to 'JARDINERIA'@'%';
use JARDINERIA;

CREATE TABLE GAMA_PRODUCTO(
GAMA VARCHAR(50),
DESCRIPCION_TEXTO VARCHAR(50),
DESCRIPCION_HTML VARCHAR(50),
IMAGEN VARCHAR(256),
CONSTRAINT PK_GAMA PRIMARY KEY (GAMA)
);
CREATE TABLE PRODUCTO(
CODIGO_PRODUCTO VARCHAR(15),
NOMBRE VARCHAR(70),
GAMA VARCHAR(50),
DIMENSIONES VARCHAR(25),
PROVEEDOR VARCHAR(50),
DESCRIPCION VARCHAR(50),
CANTIDAD_EN_STOCK SMALLINT(6),
PRECIO_VENTA DECIMAL(15,2),
PRECIO_PROVEEDOR DECIMAL(15,2),
CONSTRAINT PK_CODIGO_PRODUCTO PRIMARY KEY (CODIGO_PRODUCTO)
);
CREATE TABLE PEDIDO(
CODIGO_PEDIDO INT(11),
FECHA_PEDIDO DATE,
FECHA_ESPERADA DATE,
FECHA_ENTREGA DATE,
ESTADO VARCHAR(15),
COMENTARIOS VARCHAR(50),
CODIGO_CLIENTE INT(11),
CONSTRAINT PK_CODIGO_PEDIDO PRIMARY KEY (CODIGO_PEDIDO)
);
CREATE TABLE DETALLE_PEDIDO(
CODIGO_PEDIDO INT(11),
CODIGO_PRODUCTO VARCHAR(15),
CANTIDAD INT(11),
PRECIO_UNIDAD DECIMAL(15,2),
NUMERO_LINEA SMALLINT(6),
CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (CODIGO_PEDIDO,CODIGO_PRODUCTO)
);
CREATE TABLE CLIENTE(
CODIGO_CLIENTE INT(11),
NOMBRE_CLIENTE VARCHAR(50),
NOMBRE_CONTACTO VARCHAR(30),
APELLIDO_CONTACTO VARCHAR(30),
TELEFONO VARCHAR(15),
FAX VARCHAR(15),
LINEA_DIRECCION1 VARCHAR(50),
LINEA_DIRECCION2 VARCHAR(50),
CIUDAD VARCHAR(50),
REGION VARCHAR(50),
PAIS VARCHAR(50),
CODIGO_POSTAL VARCHAR(10),
CODIGO_EMPLEADO_REP_VENTAS INT(11),
LIMITE_CREDITO DECIMAL(15,2),
CONSTRAINT PK_CODIGO_CLIENTE PRIMARY KEY (CODIGO_CLIENTE)
);
CREATE TABLE PAGO(
CODIGO_CLIENTE INT(11),
FORMA_PAGO VARCHAR(40),
ID_TRANSACCION VARCHAR(50),
FECHA_PAGO DATE,
TOTAL DECIMAL(15,2),
CONSTRAINT PK_ID_TRANSACCION PRIMARY KEY (ID_TRANSACCION)
);
CREATE TABLE EMPLEADO(
CODIGO_EMPLEADO INT(11),
NOMBRE VARCHAR(50),
APELLIDO1 VARCHAR(50),
APELLIDO2 VARCHAR(50),
EXTENSION VARCHAR(10),
EMAIL VARCHAR(100),
CODIGO_OFICINA VARCHAR(10),
CODIGO_JEFE INT(11),
PUESTO VARCHAR(50),
CONSTRAINT PK_CODIGO_EMPLEADO PRIMARY KEY (CODIGO_EMPLEADO)
);
CREATE TABLE OFICINA(
CODIGO_OFICINA VARCHAR(10),
CIUDAD VARCHAR(30),
PAIS VARCHAR(50),
REGION VARCHAR(50),
CODIGO_POSTAL VARCHAR(10),
TELEFONO VARCHAR(20),
LINEA_DIRECCION1 VARCHAR(50),
LINEA_DIRECCION2 VARCHAR(50),
CONSTRAINT PK_CODIGO_OFICINA PRIMARY KEY (CODIGO_OFICINA)
);

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_GAMA FOREIGN KEY (GAMA) REFERENCES GAMA_PRODUCTO(GAMA);
ALTER TABLE DETALLE_PEDIDO ADD CONSTRAINT FK_CODIGO_PRODUCTO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO);
ALTER TABLE DETALLE_PEDIDO ADD CONSTRAINT FK_CODIGO_PEDIDO FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO(CODIGO_PEDIDO);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_CODIGO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE);
ALTER TABLE PAGO ADD CONSTRAINT FK2_CODIGO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE);
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CODIGO_EMPLEADO FOREIGN KEY (CODIGO_EMPLEADO_REP_VENTAS) REFERENCES EMPLEADO(CODIGO_EMPLEADO);
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_CODIGO_OFICINA FOREIGN KEY (CODIGO_OFICINA) REFERENCES OFICINA(CODIGO_OFICINA);
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_CODIGO_JEFE FOREIGN KEY (CODIGO_JEFE) REFERENCES EMPLEADO(CODIGO_EMPLEADO);
