CREATE TABLE EMPLEADO(
CODIGO_EMPLEADO NUMBER(11),
NOMBRE VARCHAR2(50),
APELLIDO1 VARCHAR2(50),
APELLIDO2 VARCHAR2(50),
EXTENSION VARCHAR2(10),
EMAIL VARCHAR2(100),
CODIGO_OFICINA VARCHAR2(10),
CODIGO_JEFE NUMBER(11),
PUESTO VARCHAR2(50),
CONSTRAINT PK_CODIGO_EMPLEADO PRIMARY KEY (CODIGO_EMPLEADO)
);
CREATE TABLE OFICINA(
CODIGO_OFICINA VARCHAR2(10),
CIUDAD VARCHAR2(30),
PAIS VARCHAR2(50),
REGION VARCHAR2(50),
CODIGO_POSTAL VARCHAR2(10),
TELEFONO VARCHAR2(20),
LINEA_DIRECCION1 VARCHAR2(50),
LINEA_DIRECCION2 VARCHAR2(50),
CONSTRAINT PK_CODIGO_OFICINA PRIMARY KEY (CODIGO_OFICINA)
);
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_CODIGO_OFICINA FOREIGN KEY (CODIGO_OFICINA) REFERENCES OFICINA(CODIGO_OFICINA);
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_CODIGO_JEFE FOREIGN KEY (CODIGO_JEFE) REFERENCES EMPLEADO(CODIGO_EMPLEADO);

CREATE TABLE EMPLEADO_BACKUP(
CODIGO_EMPLEADO NUMBER(11),
NOMBRE VARCHAR2(50),
APELLIDO1 VARCHAR2(50),
APELLIDO2 VARCHAR2(50),
EXTENSION VARCHAR2(10),
EMAIL VARCHAR2(100),
CODIGO_OFICINA VARCHAR2(10),
CODIGO_JEFE NUMBER(11),
PUESTO VARCHAR2(50),
CONSTRAINT PK_CODIGO_EMPLEADO_BACKUP PRIMARY KEY (CODIGO_EMPLEADO)
);

INSERT INTO OFICINA (CODIGO_OFICINA,CIUDAD,PAIS,REGION,CODIGO_POSTAL,TELEFONO,LINEA_DIRECCION1,LINEA_DIRECCION2)
VALUES (1,'SEVILLA','ESPAÑITA','ANDALUCIA','41008','645363849','CALLE ORNITORRINCO','CALLE PATO')

INSERT INTO EMPLEADO (CODIGO_EMPLEADO,NOMBRE,APELLIDO1,APELLIDO2,EXTENSION,EMAIL,CODIGO_OFICINA,CODIGO_JEFE,PUESTO)
VALUES (1,'MANOLITO','K.O','VITIENES','4576','MANOLITO@GAFOTAS.COM',1,1,'EMPLEADO')

INSERT INTO EMPLEADO_BACKUP SELECT * FROM EMPLEADO;
SELECT * FROM EMPLEADO_BACKUP