--1. Mostrar el identificador de los alumnos matriculados en cualquier asignatura excepto la '150212' y la '130113'.
SELECT DISTINCT  A.IDALUMNO 
FROM ALUMNO_ASIGNATURA A
WHERE A.IDALUMNO NOT IN (SELECT A.IDASIGNATURA 
						FROM ALUMNO_ASIGNATURA A
						WHERE A.IDASIGNATURA =150212
						AND A.IDASIGNATURA=130113);
						
--2. Mostrar el nombre de las asignaturas que tienen más créditos que "Seguridad Vial". 
SELECT DISTINCT a.NOMBRE
FROM ASIGNATURA a
WHERE a.CREDITOS >(SELECT a.CREDITOS 
					FROM ASIGNATURA a
					WHERE a.NOMBRE LIKE'%Seguridad Vial%');
					

--3. Obtener el Id de los alumnos matriculados en las asignaturas "150212" y "130113" a la vez. 
SELECT DISTINCT ALS.IDALUMNO
FROM ALUMNO_ASIGNATURA ALS,ALUMNOS_MUYREPETIDORES ALSP,ASIGNATURA A
WHERE ALS.IDASIGNATURA=A.IDASIGNATURA
AND ALSP.IDASIGNATURA=A.IDASIGNATURA
AND A.IDASIGNATURA =(SELECT A.NOMBRE
				FROM ASIGNATURA A
				WHERE A.IDASIGNATURA LIKE 150212
				AND A.IDASIGNATURA LIKE 130113);


--4. Mostrar el Id de los alumnos matriculados en las asignatura "150212" ó "130113", en una o en otra pero no en ambas a la vez. 
SELECT DISTINCT ALS.IDALUMNO
FROM ALUMNO_ASIGNATURA ALS,ALUMNOS_MUYREPETIDORES ALSP,ASIGNATURA A
WHERE ALS.IDASIGNATURA=A.IDASIGNATURA
AND ALSP.IDASIGNATURA=A.IDASIGNATURA
AND A.IDASIGNATURA =(SELECT A.NOMBRE
				FROM ASIGNATURA A
				WHERE A.IDASIGNATURA LIKE 150212
				OR A.IDASIGNATURA LIKE 130113);

--5. Mostrar el nombre de las asignaturas de la titulación "130110" cuyos costes básicos sobrepasen el coste básico promedio por asignatura en esa titulación.
SELECT NOMBRE
FROM ASIGNATURA
WHERE COSTEBASICO>(SELECT AVG(COSTEBASICO) FROM ASIGNATURA);

--6. Mostrar el identificador de los alumnos matriculados en cualquier asignatura excepto la "150212" y la "130113�?
SELECT DISTINCT IDALUMNO
FROM ALUMNO_ASIGNATURA
WHERE IDASIGNATURA <> 150212
AND IDASIGNATURA <> 130113;
--7. Mostrar el Id de los alumnos matriculados en la asignatura "150212" pero no en la "130113". 
SELECT A.IDALUMNO
FROM ALUMNO_ASIGNATURA A
WHERE IDASIGNATURA =150212
AND IDASIGNATURA <> 130113;

--8. Mostrar el nombre de las asignaturas que tienen más créditos que "Seguridad Vial". 
SELECT DISTINCT a.NOMBRE
FROM ASIGNATURA a
WHERE CREDITOS>(SELECT CREDITOS FROM ASIGNATURA WHERE UPPER(NOMBRE)='SEGURIDAD VIAL');
--9. Mostrar las personas que no son ni profesores ni alumnos.
SELECT P.NOMBRE
FROM PERSONA P
WHERE P.DNI NOT IN (SELECT PR.DNI
							FROM PROFESOR PR)
AND P.DNI NOT IN (SELECT A.DNI
							FROM ALUMNO A);
--10. Mostrar el nombre de las asignaturas que tengan más créditos. 
SELECT NOMBRE
FROM ASIGNATURA
WHERE CREDITOS =(SELECT MAX(CREDITOS)
				FROM ASIGNATURA);
--11. Lista de asignaturas en las que no se ha matriculado nadie. 
SELECT A.IDASIGNATURA
FROM ASIGNATURA A
WHERE A.IDASIGNATURA NOT IN (SELECT A.IDASIGNATURA
							FROM ALUMNOS_MUYREPETIDORES AR,ASIGNATURA A
							WHERE A.IDASIGNATURA=AR.IDASIGNATURA)
AND A.IDASIGNATURA NOT IN (SELECT A.IDASIGNATURA
							FROM ALUMNO_ASIGNATURA ASIG,ASIGNATURA A
							WHERE A.IDASIGNATURA=ASIG.IDASIGNATURA);

--12. Ciudades en las que vive algún profesor y también algún alumno. 
SELECT P.CIUDAD
FROM PERSONA P
WHERE P.DNI IN (SELECT P.DNI 
						FROM PERSONA P,PROFESOR PR
						WHERE P.DNI=PR.DNI)
AND P.DNI IN (SELECT P.DNI
				FROM PERSONA P,ALUMNO A
				WHERE P.DNI=A.DNI);