--alter session set "_oracle_script"=true;
--create user HERRERIAONAYERAY identified by HERRERIAONAYERAY;
--GRANT CONNECT, RESOURCE, DBA TO HERRERIAONAYERAY;
CREATE TABLE ENFERMO(
	COD_INSCRIPCION NUMBER(6),
	NSS VARCHAR2(10),
	NOMBRE VARCHAR(20),
	SEXO VARCHAR2(1),
	CONSTRAINT PK_ENFERMO PRIMARY KEY (COD_INSCRIPCION)
);
CREATE TABLE HABITACION(
	NUM_HAB NUMBER(6),
	NUMERO_CAMAS NUMBER(6),
	CONSTRAINT PK_HABITACION PRIMARY KEY (NUM_HAB)
);
CREATE TABLE INGRESO(
	COD_INGRESO NUMBER(6),
	COD_INSCRIPCION NUMBER(6),
	FECHA_INGRESO DATE,
	FECHA_ALTA DATE,
	NUM_HAB NUMBER(6),
	CONSTRAINT PK_INGRESO PRIMARY KEY (COD_INGRESO),
	CONSTRAINT FK_HABITACION FOREIGN KEY (NUM_HAB) REFERENCES HABITACION(NUM_HAB),
	CONSTRAINT FK_INSCRIPCION FOREIGN KEY (COD_INSCRIPCION) REFERENCES ENFERMO(COD_INSCRIPCION)
);
CREATE TABLE MEDICO(
	COD_MEDICO NUMBER(6),
	NOMBRE VARCHAR2(20),
	ESPECIALIDAD VARCHAR2(20),
	COD_DIRECTOR NUMBER(6),
	CONSTRAINT PK_MEDICO PRIMARY KEY (COD_MEDICO),
	CONSTRAINT FK_DIRECTOR FOREIGN KEY (COD_DIRECTOR) REFERENCES MEDICO(COD_MEDICO)
);
CREATE TABLE VISITA(
	COD_MEDICO NUMBER(6),
	COD_INSCRIPCION NUMBER(6),
	FECHA DATE,
	DIAGNOSTICO VARCHAR2(20),
	CONSTRAINT PK_VISITA PRIMARY KEY (COD_MEDICO,COD_INSCRIPCION),
	CONSTRAINT FK_CODMEDICO FOREIGN KEY (COD_MEDICO) REFERENCES MEDICO(COD_MEDICO),
	CONSTRAINT FK_CODINSCRIPCION FOREIGN KEY (COD_INSCRIPCION) REFERENCES ENFERMO(COD_INSCRIPCION)
);

--1
ALTER TABLE INGRESO MODIFY FECHA_INGRESO DATE DEFAULT SYSDATE;
--2
ALTER TABLE HABITACION ADD CONSTRAINT CHK_NUMHAB CHECK (NUM_HAB BETWEEN 100 AND 399);
--3
ALTER TABLE HABITACION ADD CONSTRAINT CHK_NUMCAMAS CHECK (NUMERO_CAMAS BETWEEN 0 AND 3);
--4
ALTER TABLE INGRESO ADD CONSTRAINT CHK_FECHA_ALTA CHECK ((FECHA_ALTA IS NULL) OR (FECHA_ALTA>FECHA_INGRESO));
--5
ALTER TABLE MEDICO MODIFY ESPECIALIDAD VARCHAR2(20) DEFAULT('FAM');
--6
/* POR LA CLAVE FORANEA NO SE PUEDE BORRAR
DELETE HABITACION
WHERE COD_INGRESO=0;*/
--7
ALTER TABLE MEDICO DROP CONSTRAINT FK_DIRECTOR;
ALTER TABLE MEDICO ADD CONSTRAINT FK_DIRECTOR FOREIGN KEY (COD_DIRECTOR) REFERENCES MEDICO(COD_MEDICO) ON DELETE SET NULL;
--8
ALTER TABLE VISITA DROP CONSTRAINT FK_CODMEDICO;
ALTER TABLE VISITA ADD CONSTRAINT FK_CODMEDICO FOREIGN KEY (COD_MEDICO) REFERENCES MEDICO(COD_MEDICO) ON DELETE CASCADE;
--9
ALTER TABLE INGRESO DROP CONSTRAINT FK_INSCRIPCION;
ALTER TABLE INGRESO ADD CONSTRAINT FK_INSCRIPCION FOREIGN KEY (COD_INSCRIPCION) REFERENCES ENFERMO(COD_INSCRIPCION) ON DELETE CASCADE;
ALTER TABLE VISITA DROP CONSTRAINT FK_CODINSCRIPCION;
ALTER TABLE VISITA ADD CONSTRAINT FK_CODINSCRIPCION FOREIGN KEY (COD_INSCRIPCION) REFERENCES ENFERMO(COD_INSCRIPCION) ON DELETE CASCADE;
--10
TRUNCATE TABLE HABITACION;



