--1
ALTER TABLE ENFERMO ADD CONSTRAINT CHK_SEXO CHECK (SEXO IN ('H','M'));
--2
--ES DEBIDO QUE LA PRIMARY KEY NO SE PUEDE REPETIR MÁS DE UNA VEZ,POR 
--LO TANTO NO SE PUEDE METER MÁS DE CODIGO IGUALES
--3
ALTER TABLE ENFERMO MODIFY NSS VARCHAR2(12);
--4
INSERT INTO MEDICO (COD_MEDICO,NOMBRE,ESPECIALIDAD,COD_DIRECTOR)
VALUES (1,'YERAY','ENF',1);
INSERT INTO ENFERMO (COD_INSCRIPCION,NSS,NOMBRE,SEXO)
VALUES (1,'12345678911F','CURRO','H');
INSERT INTO ENFERMO (COD_INSCRIPCION,NSS,NOMBRE,SEXO)
VALUES (2,'123456G3911F','MARIA','M');
--5
INSERT INTO HABITACION (NUM_HAB,NUMERO_CAMAS)
VALUES (102,2);
INSERT INTO INGRESO (COD_INGRESO,COD_INSCRIPCION,FECHA_INGRESO,FECHA_ALTA,NUM_HAB)
VALUES (1,1,SYSDATE,NULL,102);
--6
INSERT INTO VISITA (COD_MEDICO,COD_INSCRIPCION,FECHA,DIAGNOSTICO)
VALUES (1,1,SYSDATE,'DOLOR CABEZA');
--7
ALTER TABLE VISITA ADD FECHA_PROXIMA_VISITA DATE;
--8
UPDATE ENFERMO SET NOMBRE='JONH NIEVE', SEXO='H' WHERE COD_INSCRIPCION=1;
--9
DELETE FROM ENFERMO WHERE NSS LIKE ('12345678911F');
--10
DROP TABLE MEDICO CASCADE CONSTRAINT;
DROP TABLE INGRESO CASCADE CONSTRAINT;
DROP TABLE ENFERMO CASCADE CONSTRAINT;
DROP TABLE HABITACION CASCADE CONSTRAINT;
DROP TABLE VISITA CASCADE CONSTRAINT;

/*AUTOCOMMIT DESACTIVADO
3.1
NO VA A PODER VERLO DEBIDO A QUE CUANDO CREAMOS LA TABLA SE HIZO EL COMMIT, PERO DESPUÉS DE INTRODUCIR LOS DATOS NO POR LO QUE SOLO PUEDE VER LA TABLA.
 
3.2
SI QUEDARÁN GUARDADOS PORQUE AL CREAR LA TABLA CLIENTE SE REALIZA UN COMMIT Y TODO LO ANTERIOR QUEDA GRABADOS A FUEGO.

3.3
NO SE PUEDE VOLVER A LA SITUACIÓN INICIAL DEBIDO QUE ANTERIORMENTE HEMOS REALIZADO UN COMMIT AL CREAR LA TABLA CLIENTE.

3.4
HAY QUE REALIZAR UN COMMIT PARA QUE QUEDEN LOS DATOS PERSISTIDOS.

3.5
SI PUEDES REALIZAR UN ROLLBACK QUE TE PERMITE VOLVER AL COMMIT PERO HAY QUE TENER CUIDADO POR QUE SI HAZ REALIZADO UN COMMIT DESPUES DE BORRAR LOS DATOS NO SE PUEDE VOLVER TENDRÍAS QUE VOLVER A INTRODUCIRLOS.

3.6
ES UNA INSTRUCCIÓN QUE  PERMITE ESTABLECER UN PUNTO DE RUPTURA, TAMBIEN PERMITE SEÑALAR
UN PUNTO INTERMEDIO ENTRE EL INICIO DE LA TRANSACCIÓN Y LA SITUACIÓN ACTUAL. 
PARA VOLVER SERIA UTILIZANDO ROLLBACK TO NOMBRESAVEPOINT.

EJEMPLO:
CREATE TABLE ENFERMO(
	COD_INSCRIPCION NUMBER(6),
	NSS VARCHAR2(10),
	NOMBRE VARCHAR(20),
	SEXO VARCHAR2(1),
	CONSTRAINT PK_ENFERMO PRIMARY KEY (COD_INSCRIPCION)
);
SAVEPOINT PRIMERO;
INSERT INTO ENFERMO (COD_INSCRIPCION,NSS,NOMBRE,SEXO)
VALUES (1,'12345678911F','CURRO','H');
INSERT INTO ENFERMO (COD_INSCRIPCION,NSS,NOMBRE,SEXO)
VALUES (2,'123456G3911F','MARIA','M');

ROLLBACK TO PRIMERO;*/